import {
  BarChart,
  LineChart,
  AreaChart,
  BoxPlot,
  CandleStickChart,
  RadarChart,
  HeatMap,
  StackedBarchart,
  MultiAxisChart,
  PieChart,
  BubbleChart,
  ScatterPlot,
  DonutChart,
  PolarAreaChart,
  RadialBarChart,
  RangeBarChart,
  GroupedHorizontalBarChart,
} from "../components/charts";

export const chartConfig = [
  { title: "Bar Chart", Component: BarChart },
  { title: "Line Chart", Component: LineChart },
  { title: "Area Chart", Component: AreaChart },
  { title: "Box Plot", Component: BoxPlot },
  { title: "CandleStick", Component: CandleStickChart },
  { title: "Stacked Bar", Component: StackedBarchart },
  { title: "Radar", Component: RadarChart },
  { title: "HeatMap", Component: HeatMap },
  { title: "Multi Axis", Component: MultiAxisChart },
  { title: "Pie Chart", Component: PieChart },
  { title: "Bubble Chart", Component: BubbleChart },
  { title: "Scatter Plot", Component: ScatterPlot },
  { title: "Donut Chart", Component: DonutChart },
  { title: "Polar Area", Component: PolarAreaChart },
  { title: "Radial Bar", Component: RadialBarChart },
  { title: "Range Bar", Component: RangeBarChart },
  { title: "Grouped Horizontal", Component: GroupedHorizontalBarChart },
];
